name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master  # or 'main' if that's your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: shakib19/fastapi-deployment-info:latest

  deploy-vm1:
    needs: build-and-push
    runs-on: [self-hosted, vm-1]
    steps:
      - name: Deploy on VM 1 using docker
        run: |
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker pull shakib19/fastapi-deployment-info:latest
          docker run -d --name fastapi-app -p 8000:8000 shakib19/fastapi-deployment-info:latest

  deploy-vm2:
    needs: build-and-push
    runs-on: [self-hosted, vm-2]
    steps:
      - name: Deploy on VM 2 using docker
        run: |
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker pull shakib19/fastapi-deployment-info:latest
          docker run -d --name fastapi-app -p 8000:8000 shakib19/fastapi-deployment-info:latest

  deploy-vm3:
    needs: build-and-push
    runs-on: [self-hosted, vm-3]
    steps:
      - name: Deploy on VM 3 using docker
        run: |
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker pull shakib19/fastapi-deployment-info:latest
          docker run -d --name fastapi-app -p 8000:8000 shakib19/fastapi-deployment-info:latest
